"""initial schema

Revision ID: 960aaacb348f
Revises: 
Create Date: 2026-03-17 21:34:31.574570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960aaacb348f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_items', sa.Column('yard_inventory_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('dispatch_items_yard_item_id_fkey'), 'dispatch_items', type_='foreignkey')
    op.create_foreign_key(None, 'dispatch_items', 'yard_inventory', ['yard_inventory_id'], ['id'])
    op.drop_column('dispatch_items', 'yard_item_id')
    op.alter_column('dispatch_orders', 'dispatch_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('dispatch_orders', 'truck_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('dispatch_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_dispatch_delivery_date'), table_name='dispatch_orders')
    op.drop_index(op.f('ix_dispatch_orders_project_id'), table_name='dispatch_orders')
    op.drop_index(op.f('ix_dispatch_status'), table_name='dispatch_orders')
    op.drop_constraint(op.f('dispatch_orders_project_id_fkey'), 'dispatch_orders', type_='foreignkey')
    op.create_foreign_key(None, 'dispatch_orders', 'projects', ['project_id'], ['id'])
    op.drop_column('dispatch_orders', 'delivery_date')
    op.create_foreign_key(None, 'production_schedule', 'elements', ['element_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quality_tests', 'elements', ['element_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('yard_inventory_element_id_fkey'), 'yard_inventory', type_='foreignkey')
    op.drop_constraint(op.f('yard_inventory_schedule_id_fkey'), 'yard_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'yard_inventory', 'elements', ['element_id'], ['id'])
    op.drop_column('yard_inventory', 'status')
    op.drop_column('yard_inventory', 'schedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yard_inventory', sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yard_inventory', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'yard_inventory', type_='foreignkey')
    op.create_foreign_key(op.f('yard_inventory_schedule_id_fkey'), 'yard_inventory', 'production_schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('yard_inventory_element_id_fkey'), 'yard_inventory', 'elements', ['element_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'quality_tests', type_='foreignkey')
    op.drop_constraint(None, 'production_schedule', type_='foreignkey')
    op.add_column('dispatch_orders', sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dispatch_orders', type_='foreignkey')
    op.create_foreign_key(op.f('dispatch_orders_project_id_fkey'), 'dispatch_orders', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_dispatch_status'), 'dispatch_orders', ['status'], unique=False)
    op.create_index(op.f('ix_dispatch_orders_project_id'), 'dispatch_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_dispatch_delivery_date'), 'dispatch_orders', ['delivery_date'], unique=False)
    op.alter_column('dispatch_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('dispatch_orders', 'truck_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('dispatch_orders', 'dispatch_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('dispatch_items', sa.Column('yard_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dispatch_items', type_='foreignkey')
    op.create_foreign_key(op.f('dispatch_items_yard_item_id_fkey'), 'dispatch_items', 'yard_inventory', ['yard_item_id'], ['id'])
    op.drop_column('dispatch_items', 'yard_inventory_id')
    # ### end Alembic commands ###
